# Generated by Django 5.2.6 on 2025-09-04 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('CALL', 'Call'), ('VERBAL', 'Verbal'), ('EMAIL', 'Email'), ('OTHER', 'Other')], max_length=16)),
                ('contact_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('SNOOZED', 'Snoozed')], default='PENDING', max_length=8)),
                ('snoozed_till', models.DateTimeField(blank=True, null=True)),
                ('audio_note', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-priority', 'due_date'],
            },
        ),
    ]
