# Generated by Django 5.2.6 on 2025-09-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0002_followup_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='audio_mp3',
            field=models.FileField(blank=True, null=True, upload_to='audio_mp3/'),
        ),
    ]
