# Generated by Django 5.2.6 on 2025-09-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='formula',
            field=models.CharField(blank=True, help_text='e.g. (input1 * input2 + input3) / input4', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='input1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='input2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='input3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='input4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
